### PR TITLE
Fixes Issue3265

### LINKED ISSUE #3265: sharding-ui-frontend config file problem
- [ ] 1. Allow the creation of new config. But when activated, you must check whether you can connect to ZK and whether there is a node on zk.

- [ ] 2. When multiple configs exist, one of them cannot be edited and must be deleted and recreated.

### PR DESCRIPTION
**Pull request by menghaoranss**
Fixes #3265.

Changes proposed in this pull request:
- support edit config and registry center

### CODE REVIEW

File: shardingsphere-ui/shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/CenterConfigServiceImpl.java [hunk 1]
```diff
@@ -102,6 +103,28 @@ public CenterConfigs loadAll(String orchestrationType) {
         return result;
     }
     
+    @Override
+    public void update(CenterConfigDTO config) {
+        CenterConfigs configs = loadAll();
+        if (!config.getPrimaryName().equals(config.getName())) {
+            CenterConfig existedConfig = find(config.getName(), config.getOrchestrationType(), configs);
+            if (null != existedConfig) {
+                throw new ShardingSphereUIException(ShardingSphereUIException.SERVER_ERROR, "Center already existed!");
```
Comment (kimmking) [inline shardingsphere-ui/shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/CenterConfigServiceImpl.java]: Add name to messages.

Comment (menghaoranss) [reply shardingsphere-ui/shardingsphere-ui-backend/src/main/java/org/apache/shardingsphere/ui/servcie/impl/CenterConfigServiceImpl.java]: fixed.
