### PR TITLE
 Modify the way to identify Rule Configuration in Config Center

### LINKED ISSUE #3817: Sharding-Proxy starts up failed with Orchestration in scenario `sharding+encrypt+masterSlave`.
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-rc4
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-proxy
### Expected behavior
proxy starts up well!
### Actual behavior
proxy starts up failed!
### Reason analyze (If you can)
Sharding-Proxy gets the configuration from Configuration Center when it is initlizating. It recognizes these RuleConfiguration by key words. But there is a problem, for example:
   
   The `sharding+encrypt` rule configuration in Configuration Center as follows, Proxy recognizes these RuleConfigurations by key words (`tables:\n`-->shardingRule, `encryptors:\n`-->encryptRule ).
   We can see that there is a key word 'tables:' exists in shardingRule and encryptRule at the same time. So, we can't identify shardingRule by using key word `tables:`, it can use `encryptRule` as `shardingRule`
   or use `shardingRule` as `encryptRule` in complex scenario.( for example `sharding+encrypt`,Proxy can use `shardingRule` as `encryptRule` )

**sharding+encrypt rule configuration**
```
encryptRule:
  encryptors:
    encryptor_aes:
      props:
        aes.key.value: 123456abc
      type: aes
  tables:
    t_user:
      columns:
        user_name:
          cipherColumn: assisted_query_pwd
          encryptor: encryptor_aes
          plainColumn: user_name_plain
tables:
  t_user:
    actualDataNodes: ds_${0..1}.t_user_${0..1}
    databaseStrategy:
      inline:
        algorithmExpression: ds_${user_id % 2}
        shardingColumn: user_id
    keyGenerator:
      column: user_id
      type: SNOWFLAKE
    logicTable: t_user
    tableStrategy:
      inline:
        algorithmExpression: t_user_${user_id % 2}
        shardingColumn: user_id
```

**method**  `getSchemaRules`

image

**method**  `isShardingRule` , `isEncryptRule`

image

### PR DESCRIPTION
**Pull request by haetao**
Fixes #3817 .

### CODE REVIEW

**Comment by haetao** [comment]
./run ci

File: sharding-orchestration/sharding-orchestration-core/src/main/java/org/apache/shardingsphere/orchestration/internal/registry/config/service/ConfigurationService.java [hunk 1]
```diff
@@ -174,7 +174,13 @@ private boolean hasProperties() {
      * @return is sharding rule or not
      */
     public boolean isShardingRule(final String shardingSchemaName) {
-        return regCenter.getDirectly(configNode.getRulePath(shardingSchemaName)).contains("tables:\n");
+        if (regCenter.getDirectly(configNode.getRulePath(shardingSchemaName)).contains("encryptRule:\n")) {
```
Comment (terrymanu) [inline sharding-orchestration/sharding-orchestration-core/src/main/java/org/apache/shardingsphere/orchestration/internal/registry/config/service/ConfigurationService.java]: Incorrect if sharding only

Comment (haetao) [reply sharding-orchestration/sharding-orchestration-core/src/main/java/org/apache/shardingsphere/orchestration/internal/registry/config/service/ConfigurationService.java]: The rule configuration in registry center  format is as follows  when sharding only.
```
tables:
  t_address:
    actualDataNodes: ds_${0..1}.t_address
    logicTable: t_address
  t_order:
    actualDataNodes: ds_${0..1}.t_order_${0..1}
    databaseStrategy:
      inline:
        algorithmExpression: ds_${user_id % 2}
        shardingColumn: user_id
    keyGenerator:
      column: order_id
      type: SNOWFLAKE
    logicTable: t_order
    tableStrategy:
      inline:
        algorithmExpression: t_order_${order_id % 2}
        shardingColumn: order_id
  t_order_item:
    actualDataNodes: ds_${0..1}.t_order_item_${0..1}
    databaseStrategy:
      inline:
        algorithmExpression: ds_${user_id % 2}
        shardingColumn: user_id
    keyGenerator:
      column: order_id
      type: SNOWFLAKE
    logicTable: t_order_item
    tableStrategy:
      inline:
        algorithmExpression: t_order_item_${order_id % 2}
        shardingColumn: order_id
```

We  just make sure  the rule is not  encrypt  only. the encrypt only  rule configuration in registry center  is as follows.
```
encryptors:
    encryptor_aes:
      type: aes
      props:
        aes.key.value: 123456abc
    encryptor_md5:
      type: md5
 tables:
    t_user:
      columns:
        user_name:
          plainColumn: user_name
          cipherColumn: user_name_plain
          encryptor: encryptor_aes
```

The complex rule is as follows. it will be as  shardingRule
  ```
tables:
    t_user:
      actualDataNodes: ds_${0..1}.t_user_${0..1}
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds_${user_id % 2}
      tableStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: t_user_${user_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: user_id
  defaultTableStrategy:
    none:
      
  defaultDatabaseStrategy:
    none: 
    
  masterSlaveRules:
    ds_0:
      masterDataSourceName: ds_master_0
      slaveDataSourceNames: [ds_master_0_slave_0, ds_master_0_slave_1]
      loadBalanceAlgorithmType: ROUND_ROBIN
    ds_1:
      masterDataSourceName: ds_master_1
      slaveDataSourceNames: [ds_master_1_slave_0, ds_master_1_slave_1]
      loadBalanceAlgorithmType: ROUND_ROBIN
      
  encryptRule:
    encryptors:
      encryptor_aes:
        type: aes
        props:
          aes.key.value: 123456abc
    tables:
      t_user:
        columns:
          user_name:
            plainColumn: user_name_plain
            cipherColumn: user_name
            encryptor: encryptor_aes
```

Comment (haetao) [reply sharding-orchestration/sharding-orchestration-core/src/main/java/org/apache/shardingsphere/orchestration/internal/registry/config/service/ConfigurationService.java]: Here, In the judgement of sharding rule , we just make sure it's not encrypt only. All the complex  scenes are sharding.

Comment (haetao) [reply sharding-orchestration/sharding-orchestration-core/src/main/java/org/apache/shardingsphere/orchestration/internal/registry/config/service/ConfigurationService.java]: The difference of Rule Configuration in registry center  in  encrypt only and cmplex scene is as follows:

 **encrypt only**
```
encryptors:
    encryptor_aes:
      type: aes
      props:
        aes.key.value: 123456abc
    encryptor_md5:
      type: md5
tables:
    t_user:
      columns:
        user_name:
          plainColumn: user_name_plain
          cipherColumn: user_name
          encryptor: encryptor_md5
```
**complex scene**
```
  tables:
    t_user:
      actualDataNodes: ds_${0..1}.t_user_${0..1}
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds_${user_id % 2}
      tableStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: t_user_${user_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: user_id
  defaultTableStrategy:
    none:
      
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds_${user_id % 2}
  masterSlaveRules:
    ds_0:
      masterDataSourceName: ds_master_0
      slaveDataSourceNames: [ds_master_0_slave_0, ds_master_0_slave_1]
      loadBalanceAlgorithmType: ROUND_ROBIN
    ds_1:
      masterDataSourceName: ds_master_1
      slaveDataSourceNames: [ds_master_1_slave_0, ds_master_1_slave_1]
      loadBalanceAlgorithmType: ROUND_ROBIN
      
  encryptRule:
    encryptors:
      encryptor_aes:
        type: aes
        props:
          aes.key.value: 123456abc
    tables:
      t_user:
        columns:
          user_name:
            plainColumn: user_name_plain
            cipherColumn: user_name
            encryptor: encryptor_aes
```
