### PR TITLE
issue-4785: Check uniformed with all actual tables' meta data in once when loading them

### LINKED ISSUE #4785: Check uniformed with all actual tables' meta data in once when loading them
ShardingSphere will check uniformed for all actual tables' meta data if user config to enable meta data checking.

The current `checkUniformed()` method can only find the first violation and halt the check by throw an exception. The message of exception is included the first violated actual table only.

It will be better to check all actual tables and record all violations. After check finished, the exception can include all violations information.

The code is in `org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader`, please search `// TODO check all meta data in once` to get the check point.

### PR DESCRIPTION
**Pull request by JasonKing168**
Fixes #4785.

### CODE REVIEW

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 1]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
-            if (!sample.equals(decorator.decorate(entry.getValue(), logicTableName, shardingRule))) {
-                throw new ShardingSphereException(
-                        "Cannot get uniformed table structure for logic table `%s` and actual table `%s`. The different meta data of actual tables are as follows:\n%s\n%s.",
-                        logicTableName, entry.getKey(), sample, entry.getValue());
+            TableMetaData entryValue = entry.getValue();
+            if (!sample.equals(decorator.decorate(entryValue, logicTableName, shardingRule))) {
+                errorMetaDataList.add(new String[] {entry.getKey(), entryValue.toString()});
+            }
+        }
+
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: Please remove useless blank line

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 2]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
         return actualDefaultDataSourceName.isPresent()
                 ? SchemaMetaDataLoader.load(dataSourceMap.get(actualDefaultDataSourceName.get()), maxConnectionsSizePerQuery) : new SchemaMetaData(Collections.emptyMap());
     }
-    
-    // TODO check all meta data in once
+
     private void checkUniformed(final String logicTableName, final Map<String, TableMetaData> actualTableMetaDataMap) {
         ShardingTableMetaDataDecorator decorator = new ShardingTableMetaDataDecorator();
         TableMetaData sample = decorator.decorate(actualTableMetaDataMap.values().iterator().next(), logicTableName, shardingRule);
+        List<String[]> errorMetaDataList = new LinkedList<>();
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: The design `List<String[]>` is not clear, could you consider about define an object to process it?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java (hunk 1 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: okay

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java (hunk 2 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: yeah, from understanding and readable, I think define an object is better.

Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: I've defined a new class name of "TableMetaDataViolation" for upon problem, review again, pls, thanks.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import lombok.AllArgsConstructor;
+import lombok.Getter;
+import org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaData;
+
+/**
+ * Violations holder for checking uniformed table meta data.
+ */
+@AllArgsConstructor
+@Getter
+class TableMetaDataViolation {
```
Comment (kimmking) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java]: why add a new class?

Comment (kimmking) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java]: This entity only used in one method, an inner class is better.

Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java]: How about use @RequiredArgsConstructor? It is better for final with fields.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 4]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
-                        "Cannot get uniformed table structure for logic table `%s` and actual table `%s`. The different meta data of actual tables are as follows:\n%s\n%s.",
-                        logicTableName, entry.getKey(), sample, entry.getValue());
+            TableMetaData entryValue = entry.getValue();
+            if (!sample.equals(decorator.decorate(entryValue, logicTableName, shardingRule))) {
+                metaDataViolationList.add(new TableMetaDataViolation(entry.getKey(), entryValue));
+            }
+        }
+        if (!metaDataViolationList.isEmpty()) {
+            StringBuilder exceptionMessageBuilder = new StringBuilder("Cannot get uniformed table structure for logic table `%s`"
+                    + ",it has different meta data of actual tables are as follows:");
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: It is better to add a space after symbol, such as `,` and `:`

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 5]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
         return actualDefaultDataSourceName.isPresent()
                 ? SchemaMetaDataLoader.load(dataSourceMap.get(actualDefaultDataSourceName.get()), maxConnectionsSizePerQuery) : new SchemaMetaData(Collections.emptyMap());
     }
-    
-    // TODO check all meta data in once
+
     private void checkUniformed(final String logicTableName, final Map<String, TableMetaData> actualTableMetaDataMap) {
         ShardingTableMetaDataDecorator decorator = new ShardingTableMetaDataDecorator();
         TableMetaData sample = decorator.decorate(actualTableMetaDataMap.values().iterator().next(), logicTableName, shardingRule);
+        List<TableMetaDataViolation> metaDataViolationList = new LinkedList<>();
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: If for each only, maybe we can replace `List` as `Collection`

Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: `violations` is better than `metaDataViolationList`

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 6]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
         for (Entry<String, TableMetaData> entry : actualTableMetaDataMap.entrySet()) {
-            if (!sample.equals(decorator.decorate(entry.getValue(), logicTableName, shardingRule))) {
-                throw new ShardingSphereException(
-                        "Cannot get uniformed table structure for logic table `%s` and actual table `%s`. The different meta data of actual tables are as follows:\n%s\n%s.",
-                        logicTableName, entry.getKey(), sample, entry.getValue());
+            TableMetaData entryValue = entry.getValue();
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: How about just named `entryValue` as `tableMetaData` directly?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 7]
```diff
@@ -103,17 +104,25 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
+            if (!sample.equals(decorator.decorate(entryValue, logicTableName, shardingRule))) {
+                metaDataViolationList.add(new TableMetaDataViolation(entry.getKey(), entryValue));
+            }
+        }
+        if (!metaDataViolationList.isEmpty()) {
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: It is better to extract a new private method here

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java (hunk 3 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/TableMetaDataViolation.java]: It couldn't be final fields, because the fields would be set value in that method.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 8]
```diff
@@ -103,17 +108,43 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
+                    + " it has different meta data of actual tables are as follows: ");
+            for (TableMetaDataViolation each : metaDataViolations) {
+                exceptionMessageBuilder.append("\nactual table: ").append(each.getActualTableName())
+                        .append(", meta data: ").append(each.getTableMetaData());
+            }
+            throw new ShardingSphereException(exceptionMessageBuilder.toString(), logicTableName);
+        }
+    }
+
+    @AllArgsConstructor(access = AccessLevel.PACKAGE)
```
Comment (kimmking) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: why add accessLevel

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 9]
```diff
@@ -103,17 +108,43 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
         return actualDefaultDataSourceName.isPresent()
                 ? SchemaMetaDataLoader.load(dataSourceMap.get(actualDefaultDataSourceName.get()), maxConnectionsSizePerQuery) : new SchemaMetaData(Collections.emptyMap());
     }
-    
-    // TODO check all meta data in once
+
     private void checkUniformed(final String logicTableName, final Map<String, TableMetaData> actualTableMetaDataMap) {
         ShardingTableMetaDataDecorator decorator = new ShardingTableMetaDataDecorator();
         TableMetaData sample = decorator.decorate(actualTableMetaDataMap.values().iterator().next(), logicTableName, shardingRule);
+        Collection<TableMetaDataViolation> metaDataViolations = new LinkedList<>();
```
Comment (kimmking) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: Collection should be LinkedList.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java (hunk 8 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: removed already.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java [hunk 10]
```diff
@@ -103,17 +108,37 @@ private SchemaMetaData loadDefaultSchemaMetaData() throws SQLException {
...
     private void checkUniformed(final String logicTableName, final Map<String, TableMetaData> actualTableMetaDataMap) {
         ShardingTableMetaDataDecorator decorator = new ShardingTableMetaDataDecorator();
         TableMetaData sample = decorator.decorate(actualTableMetaDataMap.values().iterator().next(), logicTableName, shardingRule);
+        Collection<TableMetaDataViolation> violations = new LinkedList<>();
         for (Entry<String, TableMetaData> entry : actualTableMetaDataMap.entrySet()) {
-            if (!sample.equals(decorator.decorate(entry.getValue(), logicTableName, shardingRule))) {
-                throw new ShardingSphereException(
-                        "Cannot get uniformed table structure for logic table `%s` and actual table `%s`. The different meta data of actual tables are as follows:\n%s\n%s.",
-                        logicTableName, entry.getKey(), sample, entry.getValue());
+            TableMetaData tableMetaData = entry.getValue();
```
Comment (kimmking) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: unnecessary variable

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java (hunk 9 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: Be avoid using get(i) form to iterate operation affect performance, we suggest defining collection type still.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java (hunk 10 above)
Comment (JasonKing168) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/ShardingMetaDataLoader.java]: OK, it was removed.
