### PR TITLE
fix #3273, route to defaultDataSource or master when the sql without tableName

### LINKED ISSUE #3273: Default database doesn't work on sql without tables
My case is like this:
I have two db `db1` and `db2`.  `db1` ows table `t1`,`t2`,`t3`, function `f1`, and `db2` only onws `t2`. Only table `t2` was in partition, so I want sql related to `t1` , `t3`, `f1` to be executed on `db1`, only `t2` be executed on `db1` and `db2` according to it's condition value. I use the configuration `spring.shardingsphere.sharding.default-data-source-name`, now sql related to `t1` or `t3` was executed on `d1` as expected, but `f1`'s execution database was in random.  

The result I **expected** is like this,
```select 1 from t1;``` on db1
```select 1 from t3;``` on db1
**``` select f1;``` on db1**
```select 1 from t2;``` on db1,db2

The **actual** result is like this:
```select 1 from t1;``` on db1
```select 1 from t3;``` on db1
**``` select f1;``` on (db1 or db2 in random)**
```select 1 from t2;``` on db1,db2

### PR DESCRIPTION
**Pull request by RaigorJiang**
Fixes #3273.

Changes proposed in this pull request:

sharding:
-With default data source, route to default data source
-Without default data source, unicast route(stay the same)

Master-Slave:
-route to master database

### CODE REVIEW

**Comment by RaigorJiang** [comment]
`[2019-10-31T17:02:16.586Z] [INFO] There are 2 errors reported by Checkstyle 8.19 with src/resources/checkstyle_ci.xml ruleset.

[2019-10-31T17:02:16.586Z] [ERROR] src/main/java/org/apache/shardingsphere/ui/security/UserAuthenticationService.java:[45,5] (coding) DeclarationOrder: Variable access definition in wrong order.

[2019-10-31T17:02:16.586Z] [ERROR] src/main/java/org/apache/shardingsphere/ui/security/UserAuthenticationService.java:[45,18] (design) VisibilityModifier: Variable 'base64' must be private and have accessor methods.`


The failure is not in my code,  How to fix it ?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java [hunk 1]
```diff
@@ -405,7 +405,17 @@ public DataNode getDataNode(final String dataSourceName, final String logicTable
         }
         throw new ShardingConfigurationException("Cannot find actual data node for data source name: '%s' and logic table name: '%s'", dataSourceName, logicTableName);
     }
-    
+
+    /**
+     * Judge if defaultDataSourceName exists.
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java]: `defaultDataSourceName` are 4 words, please split it

Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java]: `defaultDataSourceName` are 4 words, please split them

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java [hunk 2]
```diff
@@ -405,7 +405,17 @@ public DataNode getDataNode(final String dataSourceName, final String logicTable
...
+     *
+     * @return if defaultDataSourceName exists
+     */
+    public boolean hasDefaultDataSourceName() {
+        String defaultDataSourceName = shardingDataSourceNames.getDefaultDataSourceName();
+        return !Strings.isNullOrEmpty(defaultDataSourceName);
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java]: Could you confirm when defaultDataSourceName is null, when defaultDataSourceName is empty string?

File: sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java [hunk 3]
```diff
@@ -70,10 +70,15 @@
...
-        return containsLockSegment(sqlStatement) || !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited() || HintManager.isMasterRouteOnly();
+        return containsLockSegment(sqlStatement) || !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited()
+                || HintManager.isMasterRouteOnly() || isSelectWithoutTable(sqlStatement);
     }
 
     private boolean containsLockSegment(final SQLStatement sqlStatement) {
         return sqlStatement instanceof SelectStatement && ((SelectStatement) sqlStatement).getLock().isPresent();
     }
+
+    private boolean isSelectWithoutTable(final SQLStatement sqlStatement) {
```
Comment (terrymanu) [inline sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: Sorry, here we need discuss again.
If it is a select SQL without table, route to slave database is fine, is it?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java (hunk 2 above)
Comment (RaigorJiang) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java]: did you mean to add some test cases?

File: sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java (hunk 3 above)
Comment (RaigorJiang) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: If it is not a  SelectStatement, it's already route to master.   so  we don't need to make any change in Master-Slave mode?

Comment (RaigorJiang) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: In this case, do we just need to consider the sharding mode?

Comment (terrymanu) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: > If it is not a SelectStatement, it's already route to master. so we don't need to make any change in Master-Slave mode?

We have another judgement to judge select statement, right?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java (hunk 1 above)
Comment (RaigorJiang) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/ShardingRule.java]: ok

File: sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java (hunk 3 above)
Comment (RaigorJiang) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: Yes,  according to my understanding,  from the code :
`!(sqlStatement instanceof SelectStatement)`,
If it is a select statement, it will be routed to slave database,  no matter whether the select SQL has a table name.
For #3273, if it is fine , we can remove the `isSelectWithoutTable ` judgement.
It means we don't need to make any change with `MasterSlaveRouter`, Do I understand it correctly?

Comment (terrymanu) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: Yes, correctly. we can do it like this way.

Comment (RaigorJiang) [reply sharding-core/sharding-core-route/src/main/java/org/apache/shardingsphere/core/route/router/masterslave/MasterSlaveRouter.java]: OK,  thank you.

**Comment by terrymanu** [comment]
> `[2019-10-31T17:02:16.586Z] [INFO] There are 2 errors reported by Checkstyle 8.19 with src/resources/checkstyle_ci.xml ruleset.
> 
> [2019-10-31T17:02:16.586Z] [ERROR] src/main/java/org/apache/shardingsphere/ui/security/UserAuthenticationService.java:[45,5] (coding) DeclarationOrder: Variable access definition in wrong order.
> 
> [2019-10-31T17:02:16.586Z] [ERROR] src/main/java/org/apache/shardingsphere/ui/security/UserAuthenticationService.java:[45,18] (design) VisibilityModifier: Variable 'base64' must be private and have accessor methods.`
> 
> The failure is not in my code, How to fix it ?

Don't worry, I have fixed at #3428.
