### PR TITLE
#4042, Use the two-stage parsing strategy

### LINKED ISSUE #4042: Use the two-stage parsing strategy
The first step uses a slightly weaker parsing strategy, SLL(\*), that almost always works. If the first parsing step fails, try the full LL(\*) parse.

After failing the first step, we don't know whether it's a true syntax error or whether it's because the SLL(\*) strategy wasn't strong enough.  Input that passes the SLL(\*) step is guaranteed to pass the full LL(\*) , so there's no point in trying out that more expensive stratety. Input fails the second step is truly syntactically invalid.

### PR DESCRIPTION
**Pull request by tuohai666**
Fixes #4042.

### CODE REVIEW

File: shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/parser/SQLParserEngine.java [hunk 1]
```diff
@@ -51,7 +57,18 @@
...
      */
     public SQLAST parse() {
-        ParseTree parseTree = SQLParserFactory.newInstance(databaseTypeName, sql).execute().getChild(0);
+        SQLParser sqlParser = SQLParserFactory.newInstance(databaseTypeName, sql);
+        ParseTree parseTree;
+        try {
+            ((Parser) sqlParser).setErrorHandler(new BailErrorStrategy());
+            ((Parser) sqlParser).getInterpreter().setPredictionMode(PredictionMode.SLL);
+            parseTree = sqlParser.execute().getChild(0);
+        } catch (ParseCancellationException ex) {
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/parser/SQLParserEngine.java]: should add final for exception catch

Comment (tuohai666) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/parser/SQLParserEngine.java]: fixed
