### PR TITLE
Fix encryption rules do not support uppercase fileds

### LINKED ISSUE #3309: Encryption rules do not support uppercase fields
### Which version of ShardingSphere did you use?
4.0.0-RC3-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Sql:
```
 <insert id="saveSysUser" parameterType="com.mlt.demo.entity.SysUser">
		insert into SYS_USER (ID,
		 NAME,
		 AGE)
		values (#{id,jdbcType=VARCHAR},
                #{name,jdbcType=VARCHAR},
                #{age,jdbcType=VARCHAR}
		)
	</insert>
```

Config:

```
spring:
  shardingsphere:
    datasource:
    ···
    
    encrypt:
      encryptors:
        encryptor_aes:
          type: aes
          props:
            aes.key.value: aes-dg
        encryptor_md5:
          type: md5
      tables:
        SYS_USER:
          columns:
            AGE:
              plainColumn: AGE
              cipherColumn: AGE_CIPHER
              encryptor: encryptor_aes
```

error:

```Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.apache.shardingsphere.core.preprocessor.segment.insert.InsertValueContext.getValue(InsertValueContext.java:86)
	at org.apache.shardingsphere.core.rewrite.feature.encrypt.parameter.impl.EncryptInsertValueParameterRewriter.encryptInsertValues(EncryptInsertValueParameterRewriter.java:75)
	at org.apache.shardingsphere.core.rewrite.feature.encrypt.parameter.impl.EncryptInsertValueParameterRewriter.rewrite(EncryptInsertValueParameterRewriter.java:63)
	at org.apache.shardingsphere.core.rewrite.feature.encrypt.context.EncryptSQLRewriteContextDecorator.decorate(EncryptSQLRewriteContextDecorator.java:43)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.getSQLUnit(EncryptPreparedStatement.java:157)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.execute(EncryptPreparedStatement.java:127)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 52 more
```

### PR DESCRIPTION
**Pull request by HongJinFeng**
Fixes #3309 
Method rewrite of class EncryptInsertValueParameterRewriter get encryptor by logic column, which is got from SQLStatementContext and formated to lower case by orm frame(like mybatis) . So if encryption rule use upper case logic column, the rewrite method can not get encryptor by it. And then Encrypt-JDBC fail to rewrite the SQL.

Changes proposed in this pull request:
The method findPlainColumn and findShardingEncryptor use the lower case logic column as parameter, and  if the encryption rule  use upper case logic column, it  cause the problem.

### CODE REVIEW

**Comment by SteNicholas** [comment]
Any unit test? And check the CI result.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java [hunk 1]
```diff
@@ -132,7 +132,18 @@ public String getLogicColumnOfCipher(final String logicTable, final String ciphe
...
     public Optional<String> findPlainColumn(final String logicTable, final String logicColumn) {
-        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(logicColumn) : Optional.<String>absent();
+        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(getOriginColumnName(logicTable, logicColumn)) : Optional.<String>absent();
+    }
+
+    private String getOriginColumnName(final String logicTable, final String logicColumn) {
+        String result = logicColumn;
+        for (String each : tables.get(logicTable).getLogicColumns()) {
+            if (logicColumn.equals(each.toLowerCase())) {
+                result = each;
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: 1. Just return each if equals
2. use `equalsIgnoreCase` is better than `equals` and `toLowerCase`

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java [hunk 2]
```diff
@@ -132,7 +132,18 @@ public String getLogicColumnOfCipher(final String logicTable, final String ciphe
...
+                break;
+            }
+        }
+        return result;
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: What is situation if `logicColumn` cannot find? Maybe throw exception?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java [hunk 3]
```diff
@@ -153,7 +153,19 @@ public String getCipherColumn(final String logicColumn) {
      * @return optional of sharding encryptor
      */
     public Optional<String> findShardingEncryptor(final String logicColumn) {
-        return columns.containsKey(logicColumn) ? Optional.of(columns.get(logicColumn).getEncryptor()) : Optional.<String>absent();
+        final String originLogicColumnName = getOriginLogicColumnName(logicColumn);
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java]: Why need `final` for `originLogicColumnName` here?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java (hunk 2 above)
Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: If the logicColum cannot be found, just return the original parameter as logic parameter, it work.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java (hunk 1 above)
Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: You make sense, wait a minute.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java (hunk 3 above)
Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java]: Sorry, my problem.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java (hunk 2 above)
Comment (terrymanu) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: Hi, thank you for reply quickly.
I know return  original parameter will not break the code. I just want ti know, what is situation if logicColumn cannot find? Is it impossible? If yes, shall we use `absent` or throw exception to make the code more clear?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java [hunk 4]
```diff
@@ -132,7 +132,16 @@ public String getLogicColumnOfCipher(final String logicTable, final String ciphe
      * @return plain column
      */
     public Optional<String> findPlainColumn(final String logicTable, final String logicColumn) {
-        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(logicColumn) : Optional.<String>absent();
+        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(getOriginColumnName(logicTable, logicColumn)) : Optional.<String>absent();
+    }
+
+    private String getOriginColumnName(final String logicTable, final String logicColumn) {
```
Comment (SteNicholas) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: It is recommended to use Guava package to shorten this code logic.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java [hunk 5]
```diff
@@ -153,7 +153,17 @@ public String getCipherColumn(final String logicColumn) {
      * @return optional of sharding encryptor
      */
     public Optional<String> findShardingEncryptor(final String logicColumn) {
-        return columns.containsKey(logicColumn) ? Optional.of(columns.get(logicColumn).getEncryptor()) : Optional.<String>absent();
+        String originLogicColumnName = getOriginLogicColumnName(logicColumn);
+        return columns.containsKey(originLogicColumnName) ? Optional.of(columns.get(getOriginLogicColumnName(logicColumn)).getEncryptor()) : Optional.<String>absent();
+    }
+
+    private String getOriginLogicColumnName(final String logicColumn) {
```
Comment (SteNicholas) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java]: It is recommended to use Guava package to shorten this code logic.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java (hunk 2 above)
Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: Of course it is possible. If the logicColumn can not be found as well as the encryptor, it is normal which means we do not need to encrypt the column. See the source code methods by this step:
1.1.1  org.apache.shardingsphere.sql.rewriter.encrypt.parameter.impl.EncryptInsertValueParameterRewriter#rewrite
1.1.2
org.apache.shardingsphere.sql.rewriter.encrypt.parameter.impl.EncryptAssignmentParameterRewriter#rewrite
1.2
org.apache.shardingsphere.core.rule.EncryptRule#findShardingEncryptor(String,String)

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java (hunk 5 above)
Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/EncryptTable.java]: Thanks for review, and furthermore, which api do you mean?

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java (hunk 2 above)
Comment (terrymanu) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: So, how about return `Optional`? If logicColumn cannot find, just return `Optional.absent()`.
And do not need call `findPlainColumn()` if absent returned.

Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: It make sense. Let me fix it.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java [hunk 6]
```diff
@@ -132,7 +132,17 @@ public String getLogicColumnOfCipher(final String logicTable, final String ciphe
      * @return plain column
      */
     public Optional<String> findPlainColumn(final String logicTable, final String logicColumn) {
-        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(logicColumn) : Optional.<String>absent();
+        Optional<String> originColumnName = getOriginColumnName(logicTable, logicColumn);
+        return tables.containsKey(logicTable) && originColumnName.isPresent() ? tables.get(logicTable).findPlainColumn(originColumnName.get()) : Optional.<String>absent();
+    }
+
+    private Optional<String> getOriginColumnName(final String logicTable, final String logicColumn) {
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: If return value is Optional, we prefer use `findXXX` instead of `getXXX`.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java [hunk 7]
```diff
@@ -132,7 +132,17 @@ public String getLogicColumnOfCipher(final String logicTable, final String ciphe
      * @return plain column
      */
     public Optional<String> findPlainColumn(final String logicTable, final String logicColumn) {
-        return tables.containsKey(logicTable) ? tables.get(logicTable).findPlainColumn(logicColumn) : Optional.<String>absent();
+        Optional<String> originColumnName = getOriginColumnName(logicTable, logicColumn);
+        return tables.containsKey(logicTable) && originColumnName.isPresent() ? tables.get(logicTable).findPlainColumn(originColumnName.get()) : Optional.<String>absent();
```
Comment (terrymanu) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: Can you move `originColumnName.isPresent()` before `tables.containsKey(logicTable)`?

Reason:
1. Let's keep consistent with `EncryptTable.java`
2. `originColumnName.isPresent()` should judge first , if absent, the statement should circuit break, do not execute `tables.containsKey(logicTable)`

Comment (HongJinFeng) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/rule/EncryptRule.java]: Accept, had committed~
