### PR TITLE
Fix Navicat connect Sharding-Proxy no primary key error.

### LINKED ISSUE #3005: error "There is no primary key here. Update will only use exact matching of the old values of the columns here. Thus, it may update more than one record."
project: sharding-proxy
version: v3.1.0 & v4.0.0-RC2

question:
when i use navicate to connect sharding-proxy, and do double-click the table(any table), it can load all the datas but just threw the errors like "There is no primary key here. Update will only use exact matching of the old values of the columns here. Thus, it may update more than one record."

### PR DESCRIPTION
**Pull request by dongzl**
Fixes #3005 

Changes proposed in this pull request:
- `ColumnMetaData` class add `notNull` & `autoIncrement` field, to return column detail flags.
- `QueryHeader` class add `signed`, `primaryKey`, `nullable`, `autoIncrement` field.
- add `MySQLColumnFieldDetailFlag` class, is a enum class for table column all flag type.

This PR only solve this problem in sharding scenario.
If no Sharding, only Master-Slave, this error will still occur, because Master-Slave scenario, the TableMeta will not be pre loaded.

### CODE REVIEW

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java [hunk 1]
```diff
@@ -37,9 +37,9 @@
     
     private final String assistedQueryColumnName;
     
-    public EncryptColumnMetaData(final String name, final String dataType, final boolean primaryKey, 
+    public EncryptColumnMetaData(final String name, final String dataType, final boolean primaryKey, final boolean nullable, final boolean autoIncrement,
```
Comment (tuohai666) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java]: Why change the parameter to 'nullable' which meaning is opposite to 'notNull'. If 'notNull' is true, then 'nullable' will be false.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java [hunk 2]
```diff
@@ -31,7 +31,8 @@
 @ToString(callSuper = true)
 public final class ShardingGeneratedKeyColumnMetaData extends ColumnMetaData {
     
-    public ShardingGeneratedKeyColumnMetaData(final String name, final String dataType, final boolean primaryKey) {
-        super(name, dataType, primaryKey);
+    public ShardingGeneratedKeyColumnMetaData(final String name, final String dataType, final boolean primaryKey, 
+                                              final boolean nullable, final boolean autoIncrement) {
```
Comment (tuohai666) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java]: Same as above.

File: sharding-core/sharding-core-execute/src/main/java/org/apache/shardingsphere/core/execute/metadata/TableMetaDataLoader.java [hunk 3]
```diff
@@ -161,7 +165,10 @@ private boolean isTableExist(final Connection connection, final String catalog,
                 String columnName = resultSet.getString(COLUMN_NAME);
                 String columnType = resultSet.getString(TYPE_NAME);
                 boolean isPrimaryKey = primaryKeys.contains(columnName);
-                Optional<ColumnMetaData> columnMetaData = getColumnMetaData(logicTableName, columnName, columnType, isPrimaryKey, generateKeyColumnName, encryptRule, derivedColumns);
+                boolean isNullable = isPrimaryKey || resultSet.getBoolean(IS_NULLABLE);
```
Comment (tuohai666) [inline sharding-core/sharding-core-execute/src/main/java/org/apache/shardingsphere/core/execute/metadata/TableMetaDataLoader.java]: 'isNullable' means the column can be null. Why the primaryKey can be null?

File: sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/context/EncryptRuntimeContext.java [hunk 4]
```diff
@@ -87,7 +91,9 @@ private boolean isTableExist(final Connection connection, final String tableName
                 String columnName = resultSet.getString(COLUMN_NAME);
                 String columnType = resultSet.getString(TYPE_NAME);
                 boolean isPrimaryKey = primaryKeys.contains(columnName);
-                Optional<ColumnMetaData> columnMetaData = getColumnMetaData(tableName, columnName, columnType, isPrimaryKey, encryptRule, derivedColumns);
+                boolean isNullable = isPrimaryKey || resultSet.getBoolean(IS_NULLABLE);
```
Comment (tuohai666) [inline sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/context/EncryptRuntimeContext.java]: Same as above.

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/response/query/QueryHeader.java [hunk 5]
```diff
@@ -48,20 +48,44 @@
...
             this.table = tableNames.isEmpty() ? "" : tableNames.iterator().next();
+            if (resultSetMetaData.getTableName(columnIndex).isEmpty()) {
+                this.primaryKey = false;
+                this.nullable = false;
+                this.autoIncrement = false;
+            } else {
+                this.primaryKey = logicSchema.getMetaData().getTables().get(resultSetMetaData.getTableName(columnIndex)).getColumns()
+                        .get(resultSetMetaData.getColumnName(columnIndex).toLowerCase()).isPrimaryKey();
+                this.nullable = logicSchema.getMetaData().getTables().get(resultSetMetaData.getTableName(columnIndex)).getColumns()
+                        .get(resultSetMetaData.getColumnName(columnIndex).toLowerCase()).isNotNull();
```
Comment (tuohai666) [inline sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/response/query/QueryHeader.java]: How could 'isNotNull' get the right value if its value is 'nullable'?

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java [hunk 6]
```diff
@@ -31,6 +31,7 @@
  * Column definition above MySQL 4.1 packet protocol.
  * 
  * @see <a href="https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-Protocol::ColumnDefinition41">ColumnDefinition41</a>
+ * @see <a href="https://mariadb.com/kb/en/library/resultset/#column-definition-packet">Column count packet</a>
```
Comment (tuohai666) [inline sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java]: Change the title from 'Column count packet' to 'Column definition packet'.

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java [hunk 7]
```diff
@@ -69,12 +70,17 @@ public MySQLColumnDefinition41Packet(final int sequenceId, final ResultSetMetaDa
                 resultSetMetaData.getColumnLabel(columnIndex), resultSetMetaData.getColumnName(columnIndex), resultSetMetaData.getColumnDisplaySize(columnIndex), 
                 MySQLColumnType.valueOfJDBCType(resultSetMetaData.getColumnType(columnIndex)), resultSetMetaData.getScale(columnIndex));
     }
-    
+
```
Comment (tuohai666) [inline sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java]: Please don't change the original indentation.

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnFieldDetailFlag.java [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+import lombok.Getter;
+import lombok.RequiredArgsConstructor;
+
+import java.util.HashMap;
+import java.util.Map;
+
+/**
+ * MySQL Column Field Detail Flag.
+ * 
+ * @see <a href="https://mariadb.com/kb/en/library/resultset/#column-definition-packet">Column count packet</a>
```
[the remark this answers is not in the document]
Comment (dongzl) [reply sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnFieldDetailFlag.java]: I hava already fixed it.

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnFieldDetailFlag.java [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+
+    private final int value;
+
+    /**
+     * Value of integer.
+     *
+     * @param value integer value
+     * @return column field detail flag enum
+     */
+    public static MySQLColumnFieldDetailFlag valueOf(final int value) {
```
[the remark this answers is not in the document]
Comment (dongzl) [reply sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnFieldDetailFlag.java]: I hava already deleted it.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java (hunk 1 above)
Comment (dongzl) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java]: I hava already fixed it. Unified name is `notNull`.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java (hunk 2 above)
Comment (dongzl) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java]: I hava already fixed it. Unified name is `notNull`.

File: sharding-core/sharding-core-execute/src/main/java/org/apache/shardingsphere/core/execute/metadata/TableMetaDataLoader.java (hunk 3 above)
Comment (dongzl) [reply sharding-core/sharding-core-execute/src/main/java/org/apache/shardingsphere/core/execute/metadata/TableMetaDataLoader.java]: fix it.
`boolean isNotNull = isPrimaryKey || !resultSet.getBoolean(IS_NULLABLE);`

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java (hunk 6 above)
Comment (dongzl) [reply sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java]: fix

File: sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java (hunk 7 above)
Comment (dongzl) [reply sharding-proxy/sharding-proxy-transport/sharding-proxy-transport-mysql/src/main/java/org/apache/shardingsphere/shardingproxy/transport/mysql/packet/command/query/MySQLColumnDefinition41Packet.java]: fix

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/response/query/QueryHeader.java (hunk 5 above)
Comment (dongzl) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/response/query/QueryHeader.java]: Unified name is notNull.

**Comment by dongzl** [comment]
I have added test case about the modified class files. But Coverage still decreased.

The `org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration` case this problem, but I don't modified this file.

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java (hunk 1 above)
Comment (tuohai666) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java]: I have refreshed the codes, but still can see nullable.
image

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java [hunk 10]
```diff
@@ -37,9 +37,9 @@
...
                                  final String cipherColumnName, final String plainColumnName, final String assistedQueryColumnName) {
-        super(name, dataType, primaryKey);
+        super(name, dataType, primaryKey, nullable, autoIncrement);
```
Comment (tuohai666) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/EncryptColumnMetaData.java]: nullable

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java (hunk 2 above)
Comment (tuohai666) [reply sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java]: still nullable

File: sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java [hunk 11]
```diff
@@ -31,7 +31,8 @@
...
+        super(name, dataType, primaryKey, nullable, autoIncrement);
```
Comment (tuohai666) [inline sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/column/ShardingGeneratedKeyColumnMetaData.java]: Please double check the remain nullables.

**Comment by tuohai666** [comment]
> I have added test case about the modified class files. But Coverage still decreased.
> 
> The `org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration` case this problem, but I don't modified this file.
> 
> and how to increase the coverage?

I think we can ignore that file.
