### PR TITLE
Issue2010

### LINKED ISSUE #2010: Do not support connectionInitSqls config of druid connection while using datasource orchestration
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support     connectionInitSqls
### Actual behavior
do not
### Reason analyze (If you can)
connectionInitSqls config is a collection:

com.alibaba.druid.pool.DruidAbstractDataSource
```
    public Collection<String> getConnectionInitSqls() {...}
```
while uploading, only general types will be serialized, which do not include ```Collection```

io.shardingsphere.core.config.DataSourceConfiguration
```
        GENERAL_CLASS_TYPE = Sets.<Class<?>>newHashSet(boolean.class, Boolean.class, int.class, Integer.class, long.class, Long.class, String.class);
```

### PR DESCRIPTION
**Pull request by menghaoranss**
Fixes #2010  .

Changes proposed in this pull request:
- support connectionInitSqls config of dbcp and druid connection pool via spring-boot 
- support connectionInitSqls config of dbcp and druid while using orchestration

The following configurations of `connectionInitSqls` has been verified using dbcp and druid connection pools:
+ springboot
```
spring.shardingsphere.datasource.ds_0.connectionInitSqls=set names utf8mb4;,set serverTimezone=UTC;
```
+ yaml
```
connectionInitSqls:
      - set names utf8mb4;
      - set serverTimezone=UTC;
```
+ namespace
```
<property name="connectionInitSqls">
            <list>
                <value>set names utf8mb4;</value>
                <value>set serverTimezone=UTC;</value>
            </list>
</property>
```
+ Using the local and zookeeper config center, the connectionInitSqls is uploaded to the config center as: 
```
connectionInitSqls:
      - set names utf8mb4;
      - set serverTimezone=UTC;
```
+ Configure connectionInitSqls using only Configuration Center
+ Configure connectionInitSqls with UI

### CODE REVIEW

File: shardingsphere-underlying/shardingsphere-common/src/test/java/org/apache/shardingsphere/underlying/common/config/DataSourceConfigurationTest.java [hunk 1]
```diff
@@ -83,4 +88,25 @@ public void assertAddAlias() {
         assertThat(actual.getProperties().get("jdbcUrl"), is(actual.getProperties().get("url")));
         assertThat(actual.getProperties().get("username"), is(actual.getProperties().get("user")));
     }
+    
+    @Test
+    public void assertGetDataSourceConfigurationWithConnectionInitSqls() throws SQLException {
```
Comment (kimmking) [inline shardingsphere-underlying/shardingsphere-common/src/test/java/org/apache/shardingsphere/underlying/common/config/DataSourceConfigurationTest.java]: Here is a integration test.
I suggestion:
1. if do this way, it's neccesary to use HikariDataSource instead of BasicDatasource.
2. creat a table in h2 db, and set an insert sql to initSql, then check it work well by a select and compare.

Or anothor approach: 
just mock a jdbc driver behind HikariDataSource, check hikariDataSource send the initSql to mock jdbc connection/statement.

Comment (cherrylzhao) [reply shardingsphere-underlying/shardingsphere-common/src/test/java/org/apache/shardingsphere/underlying/common/config/DataSourceConfigurationTest.java]: connectionInitSqls in HikariDataSource is a String type, but we want to verify a collection type for this issue. also I found that collection type property not existed in in HikariDataSource, it seems that DBCP2 is ok for that

**Comment by kimmking** [comment]
@menghaoranss  need some help？

**Comment by menghaoranss** [comment]
> I want to know have you verify the spring-boot, spring-namespace, yaml case in orchestration mode.

@cherrylzhao , yes , i configured connectionInitSqls list via spring-boot, spring-namespace and yaml 
in orchestration,  the connectionInitSqls list uploaded to configCenter as yaml, and these sqls executed successfully. I also verified only use orchestration without local configuration, it worked well too.

File: shardingsphere-underlying/shardingsphere-common/src/test/java/org/apache/shardingsphere/underlying/common/config/DataSourceConfigurationTest.java (hunk 1 above)
Comment (menghaoranss) [reply shardingsphere-underlying/shardingsphere-common/src/test/java/org/apache/shardingsphere/underlying/common/config/DataSourceConfigurationTest.java]: > connectionInitSqls in HikariDataSource is a String type, but we want to verify a collection type for this issue. also I found that collection type property not existed in in HikariDataSource, it seems that DBCP2 is ok for that

@kimmking @cherrylzhao In HikariDataSource, the configuratoin is connectionInitSql, and it is a String type, i also veryfied HikariDataSource , it's ok. DBCP2 and Druid support Connection type,  the only difference is the return parameter of `getConnectionInitsqls` method, DBCP2 return List type, Druid return Connection type, I have done compatibility processing in the pr.
