### PR TITLE
Encrypt select statement in operator

### LINKED ISSUE #3618: Encryp-JDBC rewrite wrong sql when sql contain character '('
Encrypt-JDBC rewrite wrong sql when sql contain character '('. Besides, it works normally with the version of 4.0.0-RC2.

Version of ShardingSphere
4.0.0-RC3

JDBC I use
Encrypt-JDBC

Expected behavior
Rewrite the sql correct which is contain character '('

Actual behavior
The rewrite sql error when sql contain character '('

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.MySQL table and encrypt configuration
table：
create table t_demo{
username varchar(20),
phone varchar(20),
username_encrypt(64),
phone_encrypt(64)
}
encrypt configuration
spring.shardingsphere.datasource.name = ds
spring.shardingsphere.datasource.ds.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds.driver-class-name = com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds.url = xxx
spring.shardingsphere.datasource.ds.username = xxx
spring.shardingsphere.datasource.ds.password = xxx
spring.shardingsphere.encrypt.encryptors.encryptor_aes.type = AES
spring.shardingsphere.encrypt.tables.t_demo.columns.username.plainColumn = username
spring.shardingsphere.encrypt.tables.t_demo.columns.username.cipherColumn = username_encrypt
spring.shardingsphere.encrypt.tables.t_demo.columns.phone.plainColumn = phone
spring.shardingsphere.encrypt.tables.t_demo.columns.phone.cipherColumn = phone_encrypt
spring.shardingsphere.encrypt.tables.t_demo.columns.phone.encryptor = encryptor_aes
spring.shardingsphere.encrypt.tables.t_demo.columns.username.encryptor = encryptor_aes

2.My dao method definition
List<User> query(@Param("phoneList") List<String> phoneList);

3.My mybatis sql
<select id="query" resultMap="xxx">
        SELECT * FROM t_demo t
        WHERE
        (t.username IN
        <foreach collection="phoneList" open="(" separator="," close=")" item="phone">
            #{phone}
        </foreach>
        OR t.phone IN
        <foreach collection="phoneList" open="(" separator="," close=")" item="phone">
            #{phone}
        </foreach>)
        AND delete = 0
</select>

4.Encrypt-JDBC rewrite sql(The rewrite sql get more left parenthesis)
method: EncryptPreparedStatement.getSQLUnit(final String sql)

sql: select * from t_demo t where (t.username_encrypt in (('xxx','xxxx') or t.phone_encrypt in (('xxx','xxxx')) and delete = 0;

### PR DESCRIPTION
**Pull request by SteNicholas**
Fixes #3618.

Method `extractInExpressionSegments` of class `PredicateExtractor` extracts expression of parameters. It causes that method `getStopIndex` of class `SQLBuilder` returns the start index of expression, which make method `getConjunctionText` substring logic SQL end index is start index of expression. The return value of `getConjunctionText` includes parenthesis. Therefore, when operator is `IN` of `EncryptPredicateRightValueToken`, it is unnecessary to append `(`.

Changes proposed in this pull request:
- Remove left parenthesis of `EncryptPredicateRightValueToken` method `toStringForIn()`.

### CODE REVIEW

File: sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/token/pojo/EncryptPredicateRightValueToken.java [hunk 1]
```diff
@@ -72,7 +72,6 @@ private String toStringForEqual() {
     
     private String toStringForIn() {
         StringBuilder result = new StringBuilder();
-        result.append("(");
```
Comment (tristaZero) [inline sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/token/pojo/EncryptPredicateRightValueToken.java]: Can we fix this bug by modifying the startIndex?  By reviewing the unit test, personally it seems wired that `toStringForIn()` returns `'a', 'b')`, and `('a', 'b')` is complete string item. How about you?

File: sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/sql/SQLBuilder.java [hunk 2]
```diff
@@ -82,11 +84,21 @@ private String getConjunctionText(final SQLToken sqlToken) {
...
     private int getStartIndex(final SQLToken sqlToken) {
         int startIndex = sqlToken instanceof Substitutable ? ((Substitutable) sqlToken).getStopIndex() + 1 : sqlToken.getStartIndex();
-        return startIndex > logicSQL.length() ? logicSQL.length() : startIndex;
+        return Math.min(startIndex, logicSQL.length());
     }
     
     private int getStopIndex(final SQLToken sqlToken) {
         int currentSQLTokenIndex = sqlTokens.indexOf(sqlToken);
-        return sqlTokens.size() - 1 == currentSQLTokenIndex ? logicSQL.length() : sqlTokens.get(currentSQLTokenIndex + 1).getStartIndex();
+        if (sqlTokens.size() - 1 == currentSQLTokenIndex) {
```
Comment (tristaZero) [inline sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/sql/SQLBuilder.java]: Hi, sorry for my ambiguous expression. 

Actually, i mean we can re-define the startIndex of `EncryptPredicateRightValueToken`, from my unstanding somehow we mistake the startIndex of `EncryptPredicateRightValueToken` to inculde `(`. 

Besides, the key point is that we want the result of `toStringForIn()` is complete and esay-understanding. So there is no defference whether the the result of `toStringForIn()`  is `'a', 'b'` or '('a', 'b')', but it is lexical-meaning.

Why do not we look at `EncryptPredicateRightValueTokenGenerator` which generates `EncryptPredicateRightValueToken`.

I'd like to listen to your idea. Thx

Comment (SteNicholas) [reply sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/sql/SQLBuilder.java]: @tristaZero I would like to try to modify `EncryptPredicateRightValueToken` again.

File: sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/token/generator/impl/EncryptPredicateRightValueTokenGenerator.java [hunk 3]
```diff
@@ -79,8 +80,9 @@ private EncryptPredicateRightValueToken generateSQLToken(final EncryptCondition
     
     private EncryptPredicateRightValueToken generateSQLTokenForQueryWithCipherColumn(final EncryptCondition encryptCondition, final List<Object> originalValues) {
         List<Object> encryptedValues = getEncryptedValues(encryptCondition, originalValues);
-        return new EncryptPredicateRightValueToken(encryptCondition.getStartIndex(), encryptCondition.getStopIndex(),  
-                getPositionValues(encryptCondition.getPositionValueMap().keySet(), encryptedValues), encryptCondition.getPositionIndexMap().keySet(), encryptCondition.getOperator());
+        int startIndex = encryptCondition.getOperator().equals(ShardingOperator.IN) ? encryptCondition.getStartIndex() - 1 : encryptCondition.getStartIndex();
```
Comment (tristaZero) [inline sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/token/generator/impl/EncryptPredicateRightValueTokenGenerator.java]: Hi `EncryptPredicateRightValueToken` are created in `generateSQLTokenForQueryWithCipherColumn` and `generateSQLTokenForQueryWithoutCipherColumn`, can you double check whether one more same change is needed?

Comment (SteNicholas) [reply sharding-core/sharding-core-rewrite/src/main/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/token/generator/impl/EncryptPredicateRightValueTokenGenerator.java]: @tristaZero Please review this again lastly. Very sorry to trouble you. Thanks.
