### PR TITLE
changing HashMap to LinkedHashMap for deterministic iterations

### LINKED ISSUE #3163: Test can fail if HashMap iterates in a different order
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
dev branch: 4.0.0-RC3-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
Test cases inside `EncryptPreparedStatementTest` and `EncryptStatementTest.java ` should pass regardless of the HashMap iteration orders.
### Actual behavior
Tests can fail if the order changes
### Reason analyze (If you can)
Currently, test cases inside `EncryptPreparedStatementTest` and `EncryptStatementTest.java ` are using `dataSourceMap`, a HashMap, defined in `AbstractSQLTest`.  The testing helper function `assertResultSet` has a line like following
```
 try (Connection conn = getDatabaseTypeMap().values().iterator().next().values().iterator().next().getConnection();
...)
```
It is basically getting the first item in the map so it depends on the iterative order of HashMap. However, HashMap does not guarantee any specific order of entries. Therefore, the assertions in those test cases will fail if the order is different.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Slightly modifies the order of `DB_NAMES` in `AbstractSQLTest` will cause the test to fail.

### Example codes for reproduce this issue (such as a github link).
```
private static final List<String> DB_NAMES = Arrays.asList( "jdbc_0","encrypt", "jdbc_1");
```

### PR DESCRIPTION
**Pull request by contextshuffling**
Fixes #3163 

Changes proposed in this pull request:
- Use `LinkedHashMap` for `AbstractSQLTest`
- Modify corresponding test assertions.

### CODE REVIEW

File: sharding-jdbc/sharding-jdbc-core/src/test/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptPreparedStatementTest.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void assertInsertWithExecute() throws SQLException {
             statement.setObject(2, 'b');
             statement.execute();
         }
-        assertResultSet(3, 2, "encryptValue", "assistedEncryptValue");
+        assertResultSet(0, 2, "encryptValue", "assistedEncryptValue");
```
Comment (terrymanu) [inline sharding-jdbc/sharding-jdbc-core/src/test/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptPreparedStatementTest.java]: Why change value of result count if change order only?

Comment (contextshuffling) [reply sharding-jdbc/sharding-jdbc-core/src/test/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptPreparedStatementTest.java]: @terrymanu Thanks for pointing this out. We set the value to 0 because we observed after changing to LinkedHashMap to make iteration order deterministic that the test only passes with result set count as 0. However, after looking at it in more detail, we believe that what the tests want is to check the results in "encrypt" connection. 

Currently, the code seems to be getting the "encrypt" connection by assuming it is the first connection stored in the HashMap: [e.g., L152 of EncryptPreparedStatementTest.java](https://github.com/apache/incubator-shardingsphere/blob/382653d8b229cfb46be2219868b94821a2cef2b1/sharding-jdbc/sharding-jdbc-core/src/test/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptPreparedStatementTest.java#L152). However, given that the HashMap does not iterate deterministically, the first connection may not always be that "encrypt" one. Instead of iterating to get the first element, maybe it should explicitly get the "encrypt" connection by accessing the map?

For example, 
```
Connection conn = getDatabaseTypeMap().get(DatabaseTypes.getActualDatabaseType("H2")).get("encrypt").getConnection()
```
