### PR TITLE
Fix SCTL statement execute error with comments

### LINKED ISSUE #3092: SCTL statement get error when sql contains comments
### Which version of ShardingSphere did you use?

Dev

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-Proxy

### Expected behavior

SCTL statement can get correct results

### Actual behavior

When sql contains comments, the stcl statement will report an error.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

First i use DataGrip to execute command, and it get an error

image

so, i use command line tool to execute it, it works fine. but if sql has comments, will get error.
image

### PR DESCRIPTION
**Pull request by yanyzy**
Fixes #3092.

add trim to support sctl statement with comments

### CODE REVIEW

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java [hunk 1]
```diff
@@ -60,8 +66,9 @@
      * @return instance of text protocol backend handler
      */
     public static TextProtocolBackendHandler newInstance(final DatabaseType databaseType, final String sql, final BackendConnection backendConnection) {
-        if (sql.toUpperCase().startsWith(ShardingCTLBackendHandlerFactory.SCTL)) {
-            return ShardingCTLBackendHandlerFactory.newInstance(sql, backendConnection);
+        final String trimCommentSQL = trimSqlComment(sql);
```
Comment (cherrylzhao) [inline sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: it's better to move trimComentSQL logic to `ShardingCTLBackendHandlerFactory`

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java [hunk 2]
```diff
@@ -60,8 +66,9 @@
...
+        if (trimCommentSQL.toUpperCase().startsWith(ShardingCTLBackendHandlerFactory.SCTL)) {
+            return ShardingCTLBackendHandlerFactory.newInstance(trimCommentSQL, backendConnection);
```
Comment (cherrylzhao) [inline sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: so here should use contains method, then trim in ShardingCTLBackendHandlerFactory

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java [hunk 3]
```diff
@@ -104,4 +111,15 @@ private static TextProtocolBackendHandler createDALBackendHandler(final DALState
         }
         return new UnicastBackendHandler(sql, backendConnection);
     }
+
+    private static String trimSqlComment(final String sql) {
+        String result = sql;
+        if (sql.startsWith(COMMENT_PREFIX)) {
+            result = sql.substring(sql.indexOf(COMMENT_SUFFIX) + 2).trim();
+        }
+        if (sql.endsWith(SQL_END)) {
```
Comment (cherrylzhao) [inline sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: `;` will not be passed to proxy, please verify it again.

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java (hunk 2 above)
Comment (yanyzy) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: Yes, it looks clearer. but if sql is like 
```bash
select x from table where z="sctl:"
```
this situation is rare but also possible.

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java (hunk 3 above)
Comment (yanyzy) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: image
I think it may be that the client is unable to recognize the statement, resulting in no processing.

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java (hunk 2 above)
Comment (cherrylzhao) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: I have understood it. so I suggest you add a SCTLUtils class, it should include 2 method.

- isSCTL(final string sql )
   use regx to judge it 
- trimComment

are you agree with it?

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java (hunk 3 above)
Comment (cherrylzhao) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: ok, it beyond client, let's retain this logic

File: sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java (hunk 2 above)
Comment (yanyzy) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: Add a SCTLUtils class is a good idea! i will modify it. but i think use regx will get complicated, we need to consider sql comments, it is outside the control. on the other hand, "SCTL:" may exist in the conditional  statement. so my advice is remove comments first, and then use startWith method to judge it. what do you think of it?

Comment (cherrylzhao) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: if we remove comment first, it may effect non-sctl SQL, our parse engine can recognize these 
hint syntax. so I think we should just remove comment of sctl

Comment (yanyzy) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: Yes, so the trim method just for sctl statement,  will not affect other statements. i modified the code this way. what do you think of it?

Comment (cherrylzhao) [reply sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/text/TextProtocolBackendHandlerFactory.java]: ok, I have got it, it's no problem.
