### PR TITLE
hide assistedQueryColumn and show logicColumn when desc EncryptTable

### LINKED ISSUE #2784: Wrong resultSet when execute `desc table;` using EncryptRule
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
When execute `desc encryptTable`, it will show logic columns of encryptTable
### Actual behavior
when execute `desc encryptTable`, it shows actual columns of encryptTable
### Example codes for reproduce this issue (such as a github link).
The coding entrance:
```
JDBCDatabaseCommunicationEngine.java
 private BackendResponse merge(final SQLRouteResult routeResult) throws SQLException {
        if (response instanceof UpdateResponse) {
            if (!isAllBroadcastTables(routeResult.getOptimizedStatement())) {
                ((UpdateResponse) response).mergeUpdateCount();
            }
            return response;
        }
        mergedResult = MergeEngineFactory.newInstance(databaseType, 
                logicSchema.getShardingRule(), routeResult, logicSchema.getMetaData().getTable(), ((QueryResponse) response).getQueryResults()).merge();
        if (mergedResult instanceof ShowTablesMergedResult) {
            ((ShowTablesMergedResult) mergedResult).resetColumnLabel(logicSchema.getName());
        }
        handleColumnsForQueryHeader(routeResult);
        return response;
    }
```
> You need to replace actual columns of BackendResponse with logic columns here.

Here are some ideas:
1.  Create DescribeTableMergedResult extends MemoryMergedResult to handle QueryResults of `DESC encryptTable`, but U need to pass ShardingRuel not EncryptRule to DALMergeEngine
2. Modify BackendResponse in merge() of JDBCDatabaseCommunicationEngine

### PR DESCRIPTION
**Pull request by betterjava**
Fixes #2784.

Changes proposed in this pull request:
- hide assistedQueryColumn and show logicColumn when  desc EncryptTable

### CODE REVIEW

**Comment by tristaZero** [comment]
Hi, @betterjava I am sorry for not giving your reply quickly, after reviewing your pr, it is great, i think. But this issue need to be updated, i think it is also easy for u, so can u try to modify this pr to make this feature better?
**The updated issue is:**
> Instead of hiding the AssistedQueryColumns, we should show the logicColumns to users. i.e, You need to hide all the AssistedQueryColumns and cipherColumns, and show encryptColumns to user.
One encryptDataSource may contain mulitple encryptTables, and one encryptTable may contain multiple encryptColumns, and one encryptColumn may contain AssistedQueryColumn and cipherColumn. You can read EncryptTable.java to learn the relationship of them.
Therefore, we want user see the names of encryptColumn, not AssistedQueryColumn or cipherColumn.

**Comment by betterjava** [comment]
@tristaZero I changed some logic as my understanding,you can review if you have time.

**Comment by tristaZero** [comment]
@betterjava Hi, great! You get the point. Moreover, can u make write a function for
```
for (QueryResult each : queryResults) {
            while (each.next()) {
                MemoryQueryResultRow memoryResultSetRow = new MemoryQueryResultRow(each);
                if (encrypted) {
                    EncryptTable encryptTable = tables.get(logicTableName);
                    String columnName = memoryResultSetRow.getCell(1).toString();
                    if (encryptTable.getAssistedQueryColumns().contains(columnName)) {
                        continue;
                    }
                    if (encryptTable.getCipherColumns().contains(columnName)) {
                        memoryResultSetRow.setCell(1, encryptTable.getLogicColumn(columnName));
                    }
                }
                result.add(memoryResultSetRow);
            }
        }
```
So that others will read it easily. :)

**Comment by betterjava** [comment]
@tristaZero you can review again.
I think readability is first, efficiency is second,so I move some logic in loop.

**Comment by tristaZero** [comment]
@betterjava Readability is important, i will give u feekback asap.

File: sharding-core/sharding-core-merge/src/main/java/org/apache/shardingsphere/core/merge/dal/desc/DescribeTableMergedResult.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+import java.util.LinkedList;
+import java.util.List;
+import java.util.Map;
+
+/**
+ * Merged result for desc table.
+ *
+ * @author liya
+ */
+public class DescribeTableMergedResult extends MemoryMergedResult {
```
Comment (tristaZero) [inline sharding-core/sharding-core-merge/src/main/java/org/apache/shardingsphere/core/merge/dal/desc/DescribeTableMergedResult.java]: Please set it as final.

File: sharding-core/sharding-core-merge/src/test/java/org/apache/shardingsphere/core/merge/dal/desc/DescribeTableMergedResultTest.java [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+import java.util.List;
+import java.util.Map;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertFalse;
+import static org.junit.Assert.assertTrue;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+public class DescribeTableMergedResultTest {
```
Comment (tristaZero) [inline sharding-core/sharding-core-merge/src/test/java/org/apache/shardingsphere/core/merge/dal/desc/DescribeTableMergedResultTest.java]: If it will not be extended, please set it final class.

File: sharding-core/sharding-core-merge/src/test/java/org/apache/shardingsphere/core/merge/fixture/DescribeQueryResultFixture.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+import java.util.Iterator;
+
+
+/**
+ * fixture for test DescribeTableMergedResult.
+ *
+ * @author liya
+ */
+@RequiredArgsConstructor
+public class DescribeQueryResultFixture implements QueryResult {
```
Comment (tristaZero) [inline sharding-core/sharding-core-merge/src/test/java/org/apache/shardingsphere/core/merge/fixture/DescribeQueryResultFixture.java]: Should it be final?

**Comment by tristaZero** [comment]
@betterjava Good job 😉 !

**Comment by tristaZero** [comment]
I will show this pr to all the user groups, hope see your contribution again 👍
